# - name: installing nginx 
#   hosts: web
#   become: yes
#   tasks:
#   - name: Insatting nginx
#     ansible.builtin.dnf:
#       name: nginx
#       state: latest
#   - name: start and enable nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes
- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing Nginx
    ansible.builtin.dnf:
     name: nginx
     state: latest

  - name: start and enablenginx
    ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
    
  