- name: installing nginx 
  hosts: web
  become: yes
  tasks:
  - name: Insatting nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    
  