- name: variables
  hosts: localhost
  vars:
    course: "Ansible"
    trainer: "siva"
    duration: "4 months"

  task:
  - name: print the variables information
    ansible.builtin.debug:
      msg: "Hi I am learning {{course}} from trainer {{trainer}} course duration is {{duration}}"
      