- name: varibale declaring task level
  hosts: localhost
  vars:
    course: "Ansinle"
    trainer: "siva kumar"
    duration: "4 months"
    name: "SYED ALEEF BASHA"

  tasks:
  - name: tasks level varibales
    vars: 
      course: "Devops"
    ansible.builtin.debug:
      msg: "Hi My name is {{ name }}, I am learning course {{ course}} from {{ trainer }} course learing duration is {{ duration }}"
  

  - name: print information
    ansible.builtin.debug:
    vars:
      name: "Farhana"
    ansible.builtin.debug:
      msg: " Hi my name is {{ name }}, I am learning {{ course }} from {{ trainer }} courser learning duration is {{ duration }} "